SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_RADIUS = 20
LINE_WIDTH = 2

PLAYER_TURN_SPEED = 300  # degrees per second
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWNE_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
SHOT_SPEED = 500
SHOOT_COOLDOWN = 0.3

POWERUP_RADIUS = 30
POWERUP_CHANCE = 1
POWERUP_SPAWN_INTERVAL = 5.0
MAX_POWERUPS = 2

MACHINEGUN_DURATION = 5.0
MACHINEGUN_RATE_OF_FIRE = 0.1

SPEEDUP_MULTIPLIER = 1.5
SPEEDUP_DURATION = 8.0